### ISSUE TITLE
createMultisig broken after lotus 1.5.0 reset?

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-signing-tools#364]
When trying to submit a transaction for `createMultisig` (which has been working (I think) up until the Lotus 1.5.0 upgrade), I get the following error:

```
message execution failed: exit 18, reason: caller type bafkqadlgnfwc6mzpmfrwg33vnz2a cannot exec actor type bafkqadtgnfwc6mrpnv2wy5djonuwo (RetCode=18)
```

I'm guessing this has to do with the init actor changing after the fork? Wonder if the solution to this problem could be woven into a solution for https://github.com/Zondax/filecoin-signing-tools/issues/355?

**Comment by rllola** [comment]
Should be fixed with this PR : https://github.com/Zondax/filecoin-signing-tools/pull/366

**Comment by Schwartz10** [comment]
@rllola do you think something _like_ this relates to #355? (Thinking maybe an old fork broke the fil/multisig actor and thats why we can't deserialize old constructor params?)

**Comment by Schwartz10** [comment]
Hey @jleni @rllola do you know when we can expect this fix to get published in a new npm package?

**Comment by jleni** [comment]
There are problems in some dependencies upstream. We are working on that.

**Comment by Schwartz10** [comment]
Hey @rllola and @jleni - Using v0.14.0 published today does not seem to fix the problem

**Comment by EvanXzj** [comment]
When use @Zondax/filecoin-signing-tools 0.15.0 npm package,  I have encountered the same problem. do I need to upgrade sdk to solve this issue?

**Comment by rllola** [comment]
@EvanXzj Yes, you need to upgrade. Let us know if it doesn't solve your problem.

**Comment by EvanXzj** [comment]
@rllola Thanks, it solved my problem.
